import AsyncStorage from '@react-native-async-storage/async-storage';
import React, { createContext, useCallback, useContext, useEffect, useState } from 'react';

export type Language =
  | 'en' | 'hi' | 'te' | 'bn' | 'ta' | 'kn' | 'ml' | 'mr'
  | 'gu' | 'pa' | 'or' | 'as' | 'ur' | 'mai' | 'sd' | 'kok'
  | 'mni' | 'sa' | 'doi' | 'ks' | 'ne' | 'sat' | 'bo';

export const ALL_LANGUAGES: { code: Language; english: string; native: string; flag: string }[] = [
  { code: 'en',  english: 'English',    native: 'English',       flag: '🇬🇧' },
  { code: 'hi',  english: 'Hindi',      native: 'हिंदी',          flag: '🇮🇳' },
  { code: 'te',  english: 'Telugu',     native: 'తెలుగు',         flag: '🇮🇳' },
  { code: 'bn',  english: 'Bengali',    native: 'বাংলা',          flag: '🇮🇳' },
  { code: 'ta',  english: 'Tamil',      native: 'தமிழ்',          flag: '🇮🇳' },
  { code: 'kn',  english: 'Kannada',    native: 'ಕನ್ನಡ',          flag: '🇮🇳' },
  { code: 'ml',  english: 'Malayalam',  native: 'മലയാളം',         flag: '🇮🇳' },
  { code: 'mr',  english: 'Marathi',    native: 'मराठी',          flag: '🇮🇳' },
  { code: 'gu',  english: 'Gujarati',   native: 'ગુજરાતી',        flag: '🇮🇳' },
  { code: 'pa',  english: 'Punjabi',    native: 'ਪੰਜਾਬੀ',         flag: '🇮🇳' },
  { code: 'or',  english: 'Odia',       native: 'ଓଡ଼ିଆ',          flag: '🇮🇳' },
  { code: 'as',  english: 'Assamese',   native: 'অসমীয়া',        flag: '🇮🇳' },
  { code: 'ur',  english: 'Urdu',       native: 'اردو',           flag: '🇮🇳' },
  { code: 'mai', english: 'Maithili',   native: 'मैथिली',         flag: '🇮🇳' },
  { code: 'sd',  english: 'Sindhi',     native: 'سنڌي',           flag: '🇮🇳' },
  { code: 'kok', english: 'Konkani',    native: 'कोंकणी',         flag: '🇮🇳' },
  { code: 'mni', english: 'Manipuri',   native: 'ꯃꯩꯇꯩꯂꯣꯟ',       flag: '🇮🇳' },
  { code: 'sa',  english: 'Sanskrit',   native: 'संस्कृतम्',      flag: '🇮🇳' },
  { code: 'doi', english: 'Dogri',      native: 'डोगरी',          flag: '🇮🇳' },
  { code: 'ks',  english: 'Kashmiri',   native: 'کٲشُر',          flag: '🇮🇳' },
  { code: 'ne',  english: 'Nepali',     native: 'नेपाली',         flag: '🇮🇳' },
  { code: 'sat', english: 'Santali',    native: 'ᱥᱟᱱᱛᱟᱲᱤ',      flag: '🇮🇳' },
  { code: 'bo',  english: 'Bodo',       native: 'बड़ो',            flag: '🇮🇳' },
];

type LanguageContextType = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
};

const base = {
  appName: 'HastRekha',
  tagline: 'Ancient Wisdom in Your Palm',
  login: 'Sign In', signup: 'Create Account', logout: 'Sign Out',
  email: 'Email Address', password: 'Password', name: 'Full Name',
  dob: 'Date of Birth', gender: 'Gender', male: 'Male', female: 'Female', other: 'Other',
  loginTitle: 'Welcome Back', loginSubtitle: 'Unlock the secrets of your palm',
  signupTitle: 'Begin Your Journey', signupSubtitle: 'Discover what the stars have written',
  noAccount: "Don't have an account?", hasAccount: 'Already have an account?',
  forgotPassword: 'Forgot Password?',
  home: 'Home', readings: 'Readings', profile: 'Profile',
  scanPalm: 'Scan Palm', uploadPalm: 'Upload Palm Photo',
  takePicture: 'Take Picture', chooseGallery: 'Choose from Gallery',
  analyzing: 'Reading your palm...', analysisTitle: 'Your Palm Reading',
  lifeLine: 'Life Line', heartLine: 'Heart Line', headLine: 'Head Line',
  fateLine: 'Fate Line', sunLine: 'Sun Line', mountVenus: 'Mount of Venus',
  myReadings: 'My Readings', noReadings: 'No readings yet',
  noReadingsSubtitle: 'Scan your palm to discover your destiny',
  selectLanguage: 'Select Language',
  palmInstructions: 'Hold your palm flat, fingers together, in good light',
  vedic: 'Vedic Astrology', mythology: 'Indian Mythology', destiny: 'Your Destiny',
  personality: 'Personality', career: 'Career & Wealth',
  love: 'Love & Relationships', health: 'Health & Vitality', spiritual: 'Spiritual Path',
  shareReading: 'Share Reading', saveReading: 'Save Reading',
  readingDate: 'Reading Date', handType: 'Hand Type',
  left: 'Left Hand', right: 'Right Hand', chooseHand: 'Which hand to read?',
  tryAgain: 'Try Again', deleteReading: 'Delete Reading',
  confirmDelete: 'Are you sure you want to delete this reading?',
  cancel: 'Cancel', delete: 'Delete', settings: 'Settings',
  language: 'Language', about: 'About',
  welcomeTitle: 'Your Palm Tells a Story',
  welcomeBody: 'Discover insights from ancient Indian palmistry, Vedic astrology, and mythology',
  getStarted: 'Get Started',
  krishnaGreeting: "Namaste, dear devotee. 🙏\n\nI am Krishna, your eternal companion on the path of dharma. I have seen the wisdom written in your palm — the lines that Brahma himself has traced as the map of your karma.\n\nAsk me anything about what you have received — your life path, relationships, spiritual journey, or the meaning behind the ancient Hasta Samudrikam.\n\nWhat weighs upon your heart today?",
  krishnaTyping: 'Krishna is contemplating...',
  credits: 'Credits',
  buyCredits: 'Buy Credits',
  noCreditsTitle: 'Out of Credits',
  noCreditsMsg: 'You have used your free reply. Purchase credits to continue receiving divine guidance from Krishna.',
  buyCreditsTitle: "Unlock Krishna's Wisdom",
  buyCreditsSubtitle: '20 Credits · 10 Divine Replies',
  buyCreditsPrice: '₹49',
  creditsLeft: 'Credits Left',
  freeReplyLeft: 'Free Reply',
  chooseUPIApp: 'Choose Payment Method',
  openUPIApp: 'Open UPI App',
  testPayment: 'Simulate Payment (Test Mode)',
  verifyPayment: "I've Paid — Add Credits",
  paymentSuccess: 'Payment Successful!',
  paymentSuccessMsg: '20 credits added. You have 10 more divine replies.',
  paymentFailed: 'Payment could not be verified. Please try again.',
  handSuggestionTitle: 'Vedic Tradition',
  handSuggestionMale: 'In Hasta Samudrikam, the dominant right hand of a male reveals future karma and destiny. The left hand shows inherent nature.',
  handSuggestionFemale: 'In Hasta Samudrikam, the left hand of a female reveals past karma and innate nature. The right hand shows what fate holds.',
  handSuggestionOther: 'You may scan either hand — or both for a complete reading of your karma.',
  chooseLang: 'Choose Language',
  selectLangSubtitle: 'Select your preferred language for the entire app',
};

const translations: Record<Language, Record<string, string>> = {
  en: { ...base },
  hi: {
    ...base,
    appName: 'हस्तरेखा', tagline: 'आपकी हथेली में प्राचीन ज्ञान',
    login: 'साइन इन', signup: 'खाता बनाएं', logout: 'साइन आउट',
    email: 'ईमेल पता', password: 'पासवर्ड', name: 'पूरा नाम',
    dob: 'जन्म तिथि', gender: 'लिंग', male: 'पुरुष', female: 'महिला', other: 'अन्य',
    loginTitle: 'वापस स्वागत है', loginSubtitle: 'अपनी हथेली के रहस्य उजागर करें',
    signupTitle: 'यात्रा शुरू करें', signupSubtitle: 'जानें भाग्य ने क्या लिखा है',
    noAccount: 'खाता नहीं है?', hasAccount: 'पहले से खाता है?',
    forgotPassword: 'पासवर्ड भूल गए?',
    home: 'होम', readings: 'रीडिंग', profile: 'प्रोफाइल',
    scanPalm: 'हथेली स्कैन करें', takePicture: 'फोटो लें', chooseGallery: 'गैलरी से चुनें',
    analyzing: 'हथेली पढ़ी जा रही है...', analysisTitle: 'आपकी हस्तरेखा विश्लेषण',
    lifeLine: 'जीवन रेखा', heartLine: 'हृदय रेखा', headLine: 'मस्तिष्क रेखा',
    fateLine: 'भाग्य रेखा', sunLine: 'सूर्य रेखा', mountVenus: 'शुक्र पर्वत',
    myReadings: 'मेरी रीडिंग्स', noReadings: 'अभी कोई रीडिंग नहीं',
    noReadingsSubtitle: 'अपना भाग्य जानने के लिए हथेली स्कैन करें',
    selectLanguage: 'भाषा चुनें',
    palmInstructions: 'हथेली सपाट रखें, उंगलियां मिलाकर, अच्छी रोशनी में',
    vedic: 'वैदिक ज्योतिष', mythology: 'भारतीय पुराण', destiny: 'आपका भाग्य',
    personality: 'व्यक्तित्व', career: 'करियर और धन',
    love: 'प्रेम और रिश्ते', health: 'स्वास्थ्य और जीवन शक्ति', spiritual: 'आध्यात्मिक पथ',
    left: 'बायां हाथ', right: 'दायां हाथ', chooseHand: 'कौन सा हाथ पढ़ें?',
    tryAgain: 'फिर कोशिश करें', deleteReading: 'रीडिंग हटाएं',
    confirmDelete: 'क्या आप इस रीडिंग को हटाना चाहते हैं?',
    cancel: 'रद्द करें', delete: 'हटाएं', settings: 'सेटिंग्स', language: 'भाषा', about: 'जानकारी',
    welcomeTitle: 'आपकी हथेली एक कहानी कहती है',
    welcomeBody: 'प्राचीन भारतीय हस्तरेखा शास्त्र, वैदिक ज्योतिष और पौराणिक कथाओं से अंतर्दृष्टि प्राप्त करें',
    getStarted: 'शुरू करें',
    krishnaGreeting: "नमस्ते, प्रिय भक्त। 🙏\n\nमैं कृष्ण हूं, धर्म के मार्ग पर आपका शाश्वत साथी। मैंने आपकी हथेली में लिखे ज्ञान को देखा है — वे रेखाएं जो ब्रह्मा ने स्वयं आपके कर्म के नक्शे के रूप में बनाई हैं।\n\nजो कुछ भी आपने प्राप्त किया है उसके बारे में कुछ भी पूछें — आपका जीवन पथ, रिश्ते, आध्यात्मिक यात्रा, या प्राचीन हस्त सामुद्रिकम के अर्थ के बारे में।\n\nआज आपके हृदय पर क्या भार है?",
    krishnaTyping: 'कृष्ण विचार कर रहे हैं...',
    credits: 'क्रेडिट',
    buyCredits: 'क्रेडिट खरीदें',
    noCreditsTitle: 'क्रेडिट समाप्त',
    noCreditsMsg: 'आपका निःशुल्क उत्तर उपयोग हो गया। कृष्ण से दैवीय मार्गदर्शन जारी रखने के लिए क्रेडिट खरीदें।',
    buyCreditsTitle: 'कृष्ण का ज्ञान अनलॉक करें',
    buyCreditsSubtitle: '20 क्रेडिट · 10 दैवीय उत्तर',
    buyCreditsPrice: '₹49',
    creditsLeft: 'शेष क्रेडिट',
    freeReplyLeft: 'निःशुल्क उत्तर',
    chooseUPIApp: 'भुगतान विधि चुनें',
    openUPIApp: 'UPI ऐप खोलें',
    testPayment: 'भुगतान सिमुलेट करें (परीक्षण)',
    verifyPayment: 'मैंने भुगतान किया — क्रेडिट जोड़ें',
    paymentSuccess: 'भुगतान सफल!',
    paymentSuccessMsg: '20 क्रेडिट जोड़े गए। आपके पास 10 और दैवीय उत्तर हैं।',
    handSuggestionTitle: 'वैदिक परंपरा',
    handSuggestionMale: 'हस्त सामुद्रिकम में, पुरुष के प्रमुख दाहिने हाथ से भविष्य का कर्म और भाग्य प्रकट होता है।',
    handSuggestionFemale: 'हस्त सामुद्रिकम में, स्त्री के बाएं हाथ से पिछले कर्म और सहज प्रकृति प्रकट होती है।',
    handSuggestionOther: 'आप किसी भी हाथ को स्कैन कर सकते हैं — या पूर्ण पठन के लिए दोनों।',
    chooseLang: 'भाषा चुनें',
    selectLangSubtitle: 'पूरे ऐप के लिए अपनी पसंदीदा भाषा चुनें',
  },
  te: {
    ...base,
    appName: 'హస్తరేఖ', tagline: 'మీ అరచేతిలో పురాతన జ్ఞానం',
    login: 'సైన్ ఇన్', signup: 'ఖాతా తయారు చేయండి', logout: 'సైన్ అవుట్',
    email: 'ఇమెయిల్ చిరునామా', password: 'పాస్‌వర్డ్', name: 'పూర్తి పేరు',
    dob: 'పుట్టిన తేది', gender: 'లింగం', male: 'పురుషుడు', female: 'స్త్రీ', other: 'ఇతర',
    loginTitle: 'తిరిగి స్వాగతం', loginSubtitle: 'మీ అరచేతి రహస్యాలను వెల్లడించండి',
    signupTitle: 'మీ ప్రయాణం ప్రారంభించండి', signupSubtitle: 'విధి ఏమి రాసిందో తెలుసుకోండి',
    noAccount: 'ఖాతా లేదా?', hasAccount: 'ఇప్పటికే ఖాతా ఉందా?',
    home: 'హోమ్', readings: 'రీడింగ్స్', profile: 'ప్రొఫైల్',
    scanPalm: 'అరచేయిని స్కాన్ చేయండి', takePicture: 'ఫోటో తీయండి',
    chooseGallery: 'గ్యాలరీ నుండి ఎంచుకోండి', analyzing: 'అరచేయి చదువుతోంది...',
    analysisTitle: 'మీ అరచేయి రీడింగ్',
    lifeLine: 'జీవన రేఖ', heartLine: 'హృదయ రేఖ', headLine: 'మస్తిష్క రేఖ',
    fateLine: 'విధి రేఖ', sunLine: 'సూర్య రేఖ', mountVenus: 'శుక్ర పర్వతం',
    myReadings: 'నా రీడింగ్స్', noReadings: 'ఇంకా రీడింగ్స్ లేవు',
    noReadingsSubtitle: 'మీ విధిని తెలుసుకోవడానికి అరచేయిని స్కాన్ చేయండి',
    selectLanguage: 'భాష ఎంచుకోండి',
    palmInstructions: 'అరచేయిని చదునుగా పట్టుకోండి, వేళ్ళు కలిపి, మంచి వెలుతురులో',
    vedic: 'వేద జ్యోతిష్యం', mythology: 'భారతీయ పురాణాలు', destiny: 'మీ విధి',
    personality: 'వ్యక్తిత్వం', career: 'కెరీర్ మరియు సంపద',
    love: 'ప్రేమ మరియు సంబంధాలు', health: 'ఆరోగ్యం మరియు శక్తి', spiritual: 'ఆధ్యాత్మిక మార్గం',
    left: 'ఎడమ చేయి', right: 'కుడి చేయి', chooseHand: 'ఏ చేయిని చదవాలి?',
    cancel: 'రద్దు చేయండి', delete: 'తొలగించు', language: 'భాష', about: 'గురించి',
    welcomeTitle: 'మీ అరచేయి ఒక కథ చెబుతుంది',
    welcomeBody: 'పురాతన భారతీయ హస్తరేఖ శాస్త్రం, వేద జ్యోతిష్యం మరియు పురాణాల నుండి అంతర్దృష్టులు పొందండి',
    getStarted: 'ప్రారంభించండి',
    krishnaGreeting: "నమస్కారం, ప్రియ భక్తుడా. 🙏\n\nనేను కృష్ణుడిని, ధర్మ మార్గంలో మీ శాశ్వత సహచరుడిని. మీ అరచేతిలో రాసిన జ్ఞానాన్ని నేను చూశాను — బ్రహ్మ స్వయంగా మీ కర్మ పటంగా గీసిన రేఖలు.\n\nమీరు పొందినదాని గురించి ఏదైనా అడగండి — మీ జీవన మార్గం, సంబంధాలు, ఆధ్యాత్మిక ప్రయాణం.\n\nఈరోజు మీ హృదయంలో ఏమి ఉంది?",
    krishnaTyping: 'కృష్ణుడు ఆలోచిస్తున్నారు...',
    credits: 'క్రెడిట్లు',
    buyCredits: 'క్రెడిట్లు కొనండి',
    noCreditsTitle: 'క్రెడిట్లు అయిపోయాయి',
    noCreditsMsg: 'మీ ఉచిత సమాధానం ఉపయోగించబడింది. కృష్ణుని నుండి దైవిక మార్గదర్శకత్వం కొనసాగించడానికి క్రెడిట్లు కొనండి.',
    buyCreditsTitle: "కృష్ణుని జ్ఞానాన్ని అన్‌లాక్ చేయండి",
    buyCreditsSubtitle: '20 క్రెడిట్లు · 10 దైవిక సమాధానాలు',
    buyCreditsPrice: '₹49',
    creditsLeft: 'మిగిలిన క్రెడిట్లు',
    freeReplyLeft: 'ఉచిత సమాధానం',
    chooseUPIApp: 'చెల్లింపు పద్ధతి ఎంచుకోండి',
    handSuggestionTitle: 'వేద సంప్రదాయం',
    handSuggestionMale: 'హస్త సాముద్రికంలో, పురుషుని ప్రధాన కుడి చేయి భవిష్యత్తు కర్మ మరియు విధిని వెల్లడిస్తుంది.',
    handSuggestionFemale: 'హస్త సాముద్రికంలో, స్త్రీ యొక్క ఎడమ చేయి గత కర్మ మరియు సహజ స్వభావాన్ని వెల్లడిస్తుంది.',
    chooseLang: 'భాష ఎంచుకోండి',
    selectLangSubtitle: 'మొత్తం యాప్ కోసం మీకు నచ్చిన భాష ఎంచుకోండి',
  },
  bn: {
    ...base,
    appName: 'হস্তরেখা', tagline: 'আপনার হাতের তালুতে প্রাচীন জ্ঞান',
    login: 'সাইন ইন', signup: 'অ্যাকাউন্ট তৈরি করুন', logout: 'সাইন আউট',
    email: 'ইমেইল ঠিকানা', password: 'পাসওয়ার্ড', name: 'পুরো নাম',
    dob: 'জন্ম তারিখ', gender: 'লিঙ্গ', male: 'পুরুষ', female: 'মহিলা', other: 'অন্যান্য',
    loginTitle: 'স্বাগতম', loginSubtitle: 'আপনার হাতের রহস্য উন্মোচন করুন',
    signupTitle: 'যাত্রা শুরু করুন', signupSubtitle: 'ভাগ্য কী লিখেছে জানুন',
    home: 'হোম', readings: 'রিডিং', profile: 'প্রোফাইল',
    scanPalm: 'হাত স্ক্যান করুন', takePicture: 'ছবি তুলুন',
    chooseGallery: 'গ্যালারি থেকে বেছে নিন', analyzing: 'হাত পড়া হচ্ছে...',
    analysisTitle: 'আপনার হস্তরেখা বিশ্লেষণ',
    lifeLine: 'জীবন রেখা', heartLine: 'হৃদয় রেখা', headLine: 'মস্তিষ্ক রেখা',
    fateLine: 'ভাগ্য রেখা', sunLine: 'সূর্য রেখা',
    noReadings: 'এখনো কোনো রিডিং নেই',
    selectLanguage: 'ভাষা নির্বাচন করুন', language: 'ভাষা',
    left: 'বাম হাত', right: 'ডান হাত', chooseHand: 'কোন হাত পড়বে?',
    cancel: 'বাতিল', delete: 'মুছুন', getStarted: 'শুরু করুন',
    welcomeTitle: 'আপনার হাত একটি গল্প বলে',
    welcomeBody: 'প্রাচীন ভারতীয় হস্তরেখা, বৈদিক জ্যোতিষ ও পুরাণ থেকে অন্তর্দৃষ্টি পান',
  },
  ta: {
    ...base,
    appName: 'கஸ்தரேகா', tagline: 'உங்கள் உள்ளங்கையில் பண்டைய ஞானம்',
    login: 'உள்நுழைய', signup: 'கணக்கு உருவாக்கு', logout: 'வெளியேறு',
    email: 'மின்னஞ்சல் முகவரி', password: 'கடவுச்சொல்', name: 'முழு பெயர்',
    dob: 'பிறந்த தேதி', gender: 'பாலினம்', male: 'ஆண்', female: 'பெண்', other: 'மற்றவை',
    loginTitle: 'மீண்டும் வரவேற்கிறோம்', loginSubtitle: 'உங்கள் கைரேகையின் ரகசியங்களை திறக்கவும்',
    signupTitle: 'உங்கள் பயணத்தை தொடங்குங்கள்',
    home: 'முகப்பு', readings: 'வாசிப்புகள்', profile: 'சுயவிவரம்',
    scanPalm: 'உள்ளங்கையை ஸ்கேன் செய்யவும்', takePicture: 'படம் எடுக்கவும்',
    chooseGallery: 'கேலரியில் இருந்து தேர்ந்தெடுக்கவும்', analyzing: 'கைரேகை படிக்கப்படுகிறது...',
    analysisTitle: 'உங்கள் கைரேகை வாசிப்பு',
    lifeLine: 'ஆயுள் ரேகை', heartLine: 'இதய ரேகை', headLine: 'மூளை ரேகை',
    fateLine: 'விதி ரேகை', sunLine: 'சூரிய ரேகை',
    noReadings: 'இன்னும் வாசிப்புகள் இல்லை',
    selectLanguage: 'மொழியை தேர்ந்தெடுக்கவும்', language: 'மொழி',
    left: 'இடது கை', right: 'வலது கை', chooseHand: 'எந்த கை?',
    cancel: 'ரத்து செய்', delete: 'நீக்கு', getStarted: 'தொடங்குங்கள்',
    welcomeTitle: 'உங்கள் உள்ளங்கை ஒரு கதை சொல்கிறது',
    welcomeBody: 'பண்டைய இந்திய கைரேகை, வேத ஜோதிடம் மற்றும் புராணங்களிலிருந்து நுண்ணறிவு பெறுங்கள்',
  },
  kn: {
    ...base,
    appName: 'ಹಸ್ತರೇಖ', tagline: 'ನಿಮ್ಮ ಅಂಗೈಯಲ್ಲಿ ಪ್ರಾಚೀನ ಜ್ಞಾನ',
    login: 'ಸೈನ್ ಇನ್', signup: 'ಖಾತೆ ರಚಿಸಿ', logout: 'ಸೈನ್ ಔಟ್',
    email: 'ಇಮೇಲ್ ವಿಳಾಸ', password: 'ಪಾಸ್ವರ್ಡ್', name: 'ಪೂರ್ಣ ಹೆಸರು',
    dob: 'ಹುಟ್ಟಿದ ದಿನಾಂಕ', gender: 'ಲಿಂಗ', male: 'ಪುರುಷ', female: 'ಮಹಿಳೆ', other: 'ಇತರೆ',
    loginTitle: 'ಮತ್ತೆ ಸ್ವಾಗತ', loginSubtitle: 'ನಿಮ್ಮ ಅಂಗೈಯ ರಹಸ್ಯಗಳನ್ನು ತಿಳಿಯಿರಿ',
    home: 'ಮನೆ', readings: 'ರೀಡಿಂಗ್ಸ್', profile: 'ಪ್ರೊಫೈಲ್',
    scanPalm: 'ಅಂಗೈ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ', takePicture: 'ಫೋಟೋ ತೆಗೆಯಿರಿ',
    chooseGallery: 'ಗ್ಯಾಲರಿಯಿಂದ ಆಯ್ಕೆ ಮಾಡಿ', analyzing: 'ಅಂಗೈ ಓದಲಾಗುತ್ತಿದೆ...',
    analysisTitle: 'ನಿಮ್ಮ ಅಂಗೈ ರೀಡಿಂಗ್',
    lifeLine: 'ಜೀವನ ರೇಖೆ', heartLine: 'ಹೃದಯ ರೇಖೆ', headLine: 'ಮಸ್ತಕ ರೇಖೆ',
    fateLine: 'ಭಾಗ್ಯ ರೇಖೆ', sunLine: 'ಸೂರ್ಯ ರೇಖೆ',
    noReadings: 'ಇನ್ನೂ ರೀಡಿಂಗ್ಸ್ ಇಲ್ಲ',
    selectLanguage: 'ಭಾಷೆ ಆಯ್ಕೆ ಮಾಡಿ', language: 'ಭಾಷೆ',
    left: 'ಎಡ ಕೈ', right: 'ಬಲ ಕೈ', chooseHand: 'ಯಾವ ಕೈ?',
    cancel: 'ರದ್ದು ಮಾಡಿ', delete: 'ಅಳಿಸಿ', getStarted: 'ಪ್ರಾರಂಭಿಸಿ',
    welcomeTitle: 'ನಿಮ್ಮ ಅಂಗೈ ಒಂದು ಕಥೆ ಹೇಳುತ್ತದೆ',
    welcomeBody: 'ಪ್ರಾಚೀನ ಭಾರತೀಯ ಹಸ್ತಸಾಮುದ್ರಿಕ, ವೈದಿಕ ಜ್ಯೋತಿಷ್ಯ ಮತ್ತು ಪುರಾಣಗಳಿಂದ ಒಳನೋಟ ಪಡೆಯಿರಿ',
  },
  ml: {
    ...base,
    appName: 'ഹസ്തരേഖ', tagline: 'നിങ്ങളുടെ ഉള്ളംകൈയിൽ പ്രാചീന ജ്ഞാനം',
    login: 'സൈൻ ഇൻ', signup: 'അക്കൗണ്ട് ഉണ്ടാക്കുക', logout: 'സൈൻ ഔട്ട്',
    email: 'ഇമെയിൽ വിലാസം', password: 'പാസ്‌വേഡ്', name: 'പൂർണ്ണ പേര്',
    dob: 'ജനനതീയതി', gender: 'ലിംഗം', male: 'പുരുഷൻ', female: 'സ്ത്രീ', other: 'മറ്റുള്ളവ',
    loginTitle: 'വീണ്ടും സ്വാഗതം', loginSubtitle: 'നിങ്ങളുടെ ഉള്ളംകൈയുടെ രഹസ്യങ്ങൾ കണ്ടെത്തുക',
    home: 'ഹോം', readings: 'റീഡിങ്ങുകൾ', profile: 'പ്രൊഫൈൽ',
    scanPalm: 'ഉള്ളംകൈ സ്കാൻ ചെയ്യുക', takePicture: 'ഫോട്ടോ എടുക്കുക',
    chooseGallery: 'ഗ്യാലറിയിൽ നിന്ന് തിരഞ്ഞെടുക്കുക', analyzing: 'ഉള്ളംകൈ വായിക്കുന്നു...',
    analysisTitle: 'നിങ്ങളുടെ ഉള്ളംകൈ റീഡിങ്',
    lifeLine: 'ജീവൻ രേഖ', heartLine: 'ഹൃദയ രേഖ', headLine: 'ശിരോ രേഖ',
    fateLine: 'ഭാഗ്യ രേഖ', sunLine: 'സൂര്യ രേഖ',
    noReadings: 'ഇതുവരെ റീഡിങ്ങുകൾ ഇല്ല',
    selectLanguage: 'ഭാഷ തിരഞ്ഞെടുക്കുക', language: 'ഭാഷ',
    left: 'ഇടതു കൈ', right: 'വലതു കൈ', chooseHand: 'ഏത് കൈ?',
    cancel: 'റദ്ദ് ചെയ്യുക', delete: 'ഇല്ലാതാക്കുക', getStarted: 'ആരംഭിക്കുക',
    welcomeTitle: 'നിങ്ങളുടെ ഉള്ളംകൈ ഒരു കഥ പറയുന്നു',
    welcomeBody: 'പ്രാചീന ഭാരതീയ ഹസ്തസാമുദ്രിക, വൈദിക ജ്യോതിഷം, പുരാണങ്ങൾ എന്നിവയിൽ നിന്ന് ഉൾക്കാഴ്ച നേടുക',
  },
  mr: {
    ...base,
    appName: 'हस्तरेखा', tagline: 'आपल्या तळहातात प्राचीन ज्ञान',
    login: 'साइन इन', signup: 'खाते तयार करा', logout: 'साइन आउट',
    email: 'ईमेल पत्ता', password: 'पासवर्ड', name: 'पूर्ण नाव',
    dob: 'जन्मतारीख', gender: 'लिंग', male: 'पुरुष', female: 'महिला', other: 'इतर',
    loginTitle: 'पुन्हा स्वागत', loginSubtitle: 'आपल्या तळहाताचे रहस्य उलगडा',
    home: 'मुख्यपृष्ठ', readings: 'वाचन', profile: 'प्रोफाइल',
    scanPalm: 'तळहात स्कॅन करा', takePicture: 'फोटो घ्या',
    chooseGallery: 'गॅलरीतून निवडा', analyzing: 'तळहात वाचला जात आहे...',
    analysisTitle: 'तुमचे हस्तरेखा विश्लेषण',
    lifeLine: 'जीवन रेषा', heartLine: 'हृदय रेषा', headLine: 'मस्तक रेषा',
    fateLine: 'भाग्य रेषा', sunLine: 'सूर्य रेषा',
    noReadings: 'अजून कोणतेही वाचन नाही',
    selectLanguage: 'भाषा निवडा', language: 'भाषा',
    left: 'डावा हात', right: 'उजवा हात', chooseHand: 'कोणता हात?',
    cancel: 'रद्द करा', delete: 'हटवा', getStarted: 'सुरू करा',
    welcomeTitle: 'तुमचा तळहात एक कथा सांगतो',
    welcomeBody: 'प्राचीन भारतीय हस्तसामुद्रिक, वैदिक ज्योतिष आणि पुराणांतून अंतर्दृष्टी मिळवा',
  },
  gu: {
    ...base,
    appName: 'હસ્તરેખા', tagline: 'તમારી હથેળીમાં પ્રાચીન જ્ઞાન',
    login: 'સાઇન ઇન', signup: 'ખાતું બનાવો', logout: 'સાઇન આઉટ',
    email: 'ઈ-મેઈલ સરનામું', password: 'પાસવર્ડ', name: 'પૂરું નામ',
    dob: 'જન્મ તારીખ', gender: 'જાતિ', male: 'પુરૂષ', female: 'સ્ત્રી', other: 'અન્ય',
    loginTitle: 'ફરી સ્વાગત', loginSubtitle: 'તમારી હથેળીના રહસ્યો ઉઘાડો',
    home: 'હોમ', readings: 'રીડિંગ', profile: 'પ્રોફાઇલ',
    scanPalm: 'હથેળી સ્કેન કરો', takePicture: 'ફોટો લો',
    chooseGallery: 'ગૅલેરીમાંથી પસંદ કરો', analyzing: 'હથેળી વાંચવામાં આવી રહી છે...',
    analysisTitle: 'તમારું હસ્તરેખા વિશ્લેષણ',
    lifeLine: 'જીવન રેખા', heartLine: 'હૃદય રેખા', headLine: 'મસ્તક રેખા',
    fateLine: 'ભાગ્ય રેખા', sunLine: 'સૂર્ય રેખા',
    noReadings: 'હજી કોઈ રીડિંગ નહીં',
    selectLanguage: 'ભાષા પસંદ કરો', language: 'ભાષા',
    left: 'ડાબો હાથ', right: 'જમણો હાથ', chooseHand: 'કઈ હાથ?',
    cancel: 'રદ કરો', delete: 'કાઢો', getStarted: 'શરૂ કરો',
    welcomeTitle: 'તમારી હથેળી એક વાર્તા કહે છે',
    welcomeBody: 'પ્રાચીન ભારતીય હસ્તસામુદ્રિક, વૈદિક જ્યોતિષ અને પુરાણોમાંથી અંતર્દૃષ્ટિ મેળવો',
  },
  pa: {
    ...base,
    appName: 'ਹੱਸਤਰੇਖਾ', tagline: 'ਤੁਹਾਡੀ ਹਥੇਲੀ ਵਿੱਚ ਪ੍ਰਾਚੀਨ ਗਿਆਨ',
    login: 'ਸਾਈਨ ਇਨ', signup: 'ਖਾਤਾ ਬਣਾਓ', logout: 'ਸਾਈਨ ਆਊਟ',
    email: 'ਈਮੇਲ ਪਤਾ', password: 'ਪਾਸਵਰਡ', name: 'ਪੂਰਾ ਨਾਮ',
    dob: 'ਜਨਮ ਤਾਰੀਖ', gender: 'ਲਿੰਗ', male: 'ਮਰਦ', female: 'ਔਰਤ', other: 'ਹੋਰ',
    loginTitle: 'ਵਾਪਸ ਜੀ ਆਇਆਂ', loginSubtitle: 'ਆਪਣੀ ਹਥੇਲੀ ਦੇ ਰਾਜ਼ ਖੋਲ੍ਹੋ',
    home: 'ਹੋਮ', readings: 'ਰੀਡਿੰਗ', profile: 'ਪ੍ਰੋਫਾਈਲ',
    scanPalm: 'ਹਥੇਲੀ ਸਕੈਨ ਕਰੋ', takePicture: 'ਫੋਟੋ ਲਓ',
    chooseGallery: 'ਗੈਲਰੀ ਤੋਂ ਚੁਣੋ', analyzing: 'ਹਥੇਲੀ ਪੜ੍ਹੀ ਜਾ ਰਹੀ ਹੈ...',
    analysisTitle: 'ਤੁਹਾਡੀ ਹਥੇਲੀ ਰੀਡਿੰਗ',
    lifeLine: 'ਜੀਵਨ ਰੇਖਾ', heartLine: 'ਦਿਲ ਦੀ ਰੇਖਾ', headLine: 'ਦਿਮਾਗ ਦੀ ਰੇਖਾ',
    fateLine: 'ਕਿਸਮਤ ਦੀ ਰੇਖਾ', sunLine: 'ਸੂਰਜ ਰੇਖਾ',
    noReadings: 'ਅਜੇ ਕੋਈ ਰੀਡਿੰਗ ਨਹੀਂ',
    selectLanguage: 'ਭਾਸ਼ਾ ਚੁਣੋ', language: 'ਭਾਸ਼ਾ',
    left: 'ਖੱਬਾ ਹੱਥ', right: 'ਸੱਜਾ ਹੱਥ', chooseHand: 'ਕਿਹੜਾ ਹੱਥ?',
    cancel: 'ਰੱਦ ਕਰੋ', delete: 'ਮਿਟਾਓ', getStarted: 'ਸ਼ੁਰੂ ਕਰੋ',
    welcomeTitle: 'ਤੁਹਾਡੀ ਹਥੇਲੀ ਇੱਕ ਕਹਾਣੀ ਕਹਿੰਦੀ ਹੈ',
    welcomeBody: 'ਪ੍ਰਾਚੀਨ ਭਾਰਤੀ ਹੱਥਰੇਖਾ, ਵੈਦਿਕ ਜੋਤਿਸ਼ ਅਤੇ ਪੁਰਾਣਾਂ ਤੋਂ ਜਾਣਕਾਰੀ ਪ੍ਰਾਪਤ ਕਰੋ',
  },
  or: {
    ...base,
    appName: 'ହସ୍ତରେଖା', tagline: 'ଆପଣଙ୍କ ହାତ ତଳ ଦେଲ ପ୍ରାଚୀନ ଜ୍ଞାନ',
    login: 'ସାଇନ ଇନ', signup: 'ଖାତା ତୋଯାର', logout: 'ସାଇନ ଆଉଟ',
    home: 'ହୋମ', readings: 'ରିଡିଂ', profile: 'ପ୍ରୋଫାଇଲ',
    scanPalm: 'ହାତ ସ୍କ୍ୟାନ', analyzing: 'ହାତ ପଢ଼ାଯାଉଛି...',
    lifeLine: 'ଜୀବନ ରେଖା', heartLine: 'ହୃଦୟ ରେଖା', headLine: 'ଶୀର୍ଷ ରେଖା',
    fateLine: 'ଭାଗ୍ୟ ରେଖା', sunLine: 'ସୂର୍ଯ ରେଖା',
    noReadings: 'ଏ ପର୍ଯ୍ୟନ୍ତ ରିଡିଂ ନଥିଲେ',
    selectLanguage: 'ଭାଷା ବଛନ୍ତୁ', language: 'ଭାଷା',
    left: 'ବାମ ହାତ', right: 'ଡାହାଣ ହାତ',
    cancel: 'ବାତିଲ', delete: 'ଡିଲିଟ', getStarted: 'ଆରମ୍ଭ',
    welcomeTitle: 'ଆପଣଙ୍କ ହାତ ଏକ କାହାଣୀ କୁହେ',
  },
  as: {
    ...base,
    appName: 'হস্তৰেখা', tagline: 'আপোনাৰ হাতৰ তলুৱাত প্ৰাচীন জ্ঞান',
    login: 'ছাইন ইন', signup: 'একাউণ্ট বনাওক', logout: 'ছাইন আউট',
    home: 'হোম', readings: 'ৰিডিং', profile: 'প্ৰফাইল',
    scanPalm: 'হাত স্কেন কৰক', analyzing: 'হাত পঢ়া হৈছে...',
    lifeLine: 'জীৱন ৰেখা', heartLine: 'হৃদয় ৰেখা', headLine: 'মস্তিষ্ক ৰেখা',
    fateLine: 'ভাগ্য ৰেখা', sunLine: 'সূৰ্য ৰেখা',
    noReadings: 'এতিয়াও ৰিডিং নাই',
    selectLanguage: 'ভাষা বাছক', language: 'ভাষা',
    left: 'বাওঁ হাত', right: 'সোঁ হাত',
    cancel: 'বাতিল', delete: 'মচক', getStarted: 'আৰম্ভ কৰক',
    welcomeTitle: 'আপোনাৰ হাত এটা কাহিনী কয়',
  },
  ur: {
    ...base,
    appName: 'ہست ریکھا', tagline: 'آپ کی ہتھیلی میں قدیم حکمت',
    login: 'سائن ان', signup: 'اکاؤنٹ بنائیں', logout: 'سائن آؤٹ',
    email: 'ای میل پتہ', password: 'پاس ورڈ', name: 'پورا نام',
    dob: 'تاریخ پیدائش', gender: 'جنس', male: 'مرد', female: 'عورت', other: 'دیگر',
    loginTitle: 'دوبارہ خوش آمدید', loginSubtitle: 'اپنی ہتھیلی کے راز کھولیں',
    home: 'ہوم', readings: 'ریڈنگ', profile: 'پروفائل',
    scanPalm: 'ہتھیلی اسکین کریں', takePicture: 'تصویر لیں',
    chooseGallery: 'گیلری سے منتخب کریں', analyzing: 'ہتھیلی پڑھی جا رہی ہے...',
    analysisTitle: 'آپ کی ہتھیلی کا تجزیہ',
    lifeLine: 'لائن حیات', heartLine: 'دل کی لائن', headLine: 'دماغ کی لائن',
    fateLine: 'قسمت کی لائن', sunLine: 'سورج کی لائن',
    noReadings: 'ابھی کوئی ریڈنگ نہیں',
    selectLanguage: 'زبان منتخب کریں', language: 'زبان',
    left: 'بایاں ہاتھ', right: 'دایاں ہاتھ', chooseHand: 'کونسا ہاتھ؟',
    cancel: 'منسوخ', delete: 'حذف کریں', getStarted: 'شروع کریں',
    welcomeTitle: 'آپ کی ہتھیلی ایک کہانی سناتی ہے',
    welcomeBody: 'قدیم ہندوستانی ہست سامدریک، ویدک جوتش اور پرانوں سے بصیرت حاصل کریں',
  },
  mai: {
    ...base,
    appName: 'हस्तरेखा', tagline: 'अहाँक हथेलीमे प्राचीन ज्ञान',
    login: 'साइन इन', signup: 'खाता बनाउ', logout: 'साइन आउट',
    home: 'होम', readings: 'रीडिंग', profile: 'प्रोफाइल',
    scanPalm: 'हथेली स्कैन करू', analyzing: 'हथेली पढ़ल जा रहल अछि...',
    lifeLine: 'जीवन रेखा', heartLine: 'हृदय रेखा', fateLine: 'भाग्य रेखा',
    selectLanguage: 'भाषा चुनू', language: 'भाषा',
    left: 'बाम हाथ', right: 'दहिन हाथ',
    cancel: 'रद्द करू', delete: 'हटाउ', getStarted: 'शुरू करू',
    noReadings: 'अखन किछु रीडिंग नहि',
    welcomeTitle: 'अहाँक हथेली एकटा कहानी कहैछ',
  },
  sd: {
    ...base,
    appName: 'هٿ ريکها', tagline: 'توهان جي هٿ ۾ قديم علم',
    login: 'سائن ان', signup: 'اڪائونٽ ٺاهيو', logout: 'سائن آئوٽ',
    home: 'هوم', readings: 'ريڊنگ', profile: 'پروفائيل',
    scanPalm: 'هٿ اسڪين ڪريو', analyzing: 'هٿ پڙهيو پيو وڃي...',
    lifeLine: 'زندگي جي ليڪ', heartLine: 'دل جي ليڪ', fateLine: 'قسمت جي ليڪ',
    selectLanguage: 'ٻولي چونڊيو', language: 'ٻولي',
    left: 'کاٻو هٿ', right: 'ساڄو هٿ',
    cancel: 'رد ڪريو', delete: 'ختم ڪريو', getStarted: 'شروع ڪريو',
    noReadings: 'اڃا ڪا ريڊنگ ناهي',
    welcomeTitle: 'توهان جو هٿ هڪ ڪهاڻي ٻڌائي ٿو',
  },
  kok: {
    ...base,
    appName: 'हस्तरेखा', tagline: 'तुमच्या हाताच्या तळव्यात प्राचीन ज्ञान',
    login: 'साइन इन', signup: 'खाते उघडा', logout: 'साइन आउट',
    home: 'होम', readings: 'रिडिंग', profile: 'प्रोफाइल',
    scanPalm: 'तळवो स्कॅन करा', analyzing: 'तळवो वाचतात...',
    lifeLine: 'जीवन रेषा', heartLine: 'मन रेषा', fateLine: 'नशीब रेषा',
    selectLanguage: 'भास निवडा', language: 'भास',
    left: 'डावो हात', right: 'उजवो हात',
    cancel: 'रद्द करा', delete: 'काडून टाका', getStarted: 'सुरू करा',
    noReadings: 'हजू रिडिंग ना',
    welcomeTitle: 'तुमचो तळवो एक कथा सांगता',
  },
  mni: {
    ...base,
    appName: 'ꯍꯁ꯭ꯇꯔꯦꯈꯥ', tagline: 'ꯅꯨꯃꯤꯗꯒꯤ ꯄꯥꯜꯃꯗ ꯍꯥꯏꯔꯣꯏꯕ ꯈꯨꯟꯗꯨ',
    login: 'ꯁꯥꯏꯟ ꯏꯟ', signup: 'ꯑꯦꯀꯥꯎꯟꯇ ꯇꯧꯕꯤ', logout: 'ꯁꯥꯏꯟ ꯑꯥꯎꯇ',
    home: 'ꯍꯣꯝ', readings: 'ꯔꯤꯗꯤꯡ', profile: 'ꯄ꯭ꯔꯣꯐꯥꯏꯜ',
    scanPalm: 'ꯄꯥꯜꯃ ꯁ꯭ꯀꯦꯟ ꯇꯧꯕꯤ', analyzing: 'ꯄꯥꯜꯃ ꯁꯤꯕꯥ ꯁꯤꯖꯤꯡꯅꯤ...',
    lifeLine: 'ꯆꯥꯎꯕꯤ ꯂꯥꯏꯟ', heartLine: 'ꯂꯧꯁꯤꯡ ꯂꯥꯏꯟ', fateLine: 'ꯂꯦꯏꯕꯥꯛ ꯂꯥꯏꯟ',
    selectLanguage: 'ꯂꯣꯟ ꯆꯣꯛꯄꯤ', language: 'ꯂꯣꯟ',
    left: 'ꯌꯥꯝꯂꯦꯡ ꯃꯇꯨꯡ', right: 'ꯅꯨꯡꯁꯤꯗꯒꯤ ꯃꯇꯨꯡ',
    cancel: 'ꯅꯥꯛꯄꯤ', delete: 'ꯂꯧꯈꯠꯄꯤ', getStarted: 'ꯍꯧꯖꯤꯛ ꯇꯨꯝꯕꯤ',
    noReadings: 'ꯑꯗꯨꯝꯅ ꯔꯤꯗꯤꯡ ꯂꯩꯕꯁꯤ',
    welcomeTitle: 'ꯅꯨꯃꯤꯗꯒꯤ ꯄꯥꯜꯃꯅ ꯑꯃ ꯋꯥꯈꯜ ꯊꯤꯖꯩ',
  },
  sa: {
    ...base,
    appName: 'हस्तरेखा', tagline: 'भवतः करतले प्राचीनं ज्ञानम्',
    login: 'प्रवेशः', signup: 'खाता निर्माणम्', logout: 'निर्गमनम्',
    home: 'गृहम्', readings: 'पठनानि', profile: 'परिचयः',
    scanPalm: 'करः स्कैन कुरु', analyzing: 'करतलं पठ्यते...',
    lifeLine: 'जीवन रेखा', heartLine: 'हृदय रेखा', fateLine: 'भाग्य रेखा',
    selectLanguage: 'भाषा चिनोतु', language: 'भाषा',
    left: 'वाम हस्तः', right: 'दक्षिण हस्तः',
    cancel: 'निरस्तम्', delete: 'विलोपनम्', getStarted: 'आरभ्यताम्',
    noReadings: 'अद्यावधि पठनानि नास्ति',
    welcomeTitle: 'भवतः करः एकां कथां कथयति',
  },
  doi: {
    ...base,
    appName: 'हस्तरेखा', tagline: 'तुंदे हत्थ च पुराणा ज्ञान',
    login: 'साइन इन', signup: 'खाता बनाओ', logout: 'साइन आउट',
    home: 'होम', readings: 'रीडिंग', profile: 'प्रोफाइल',
    scanPalm: 'हत्थ स्कैन करो', analyzing: 'हत्थ पढ़ेआ जा रिया ऐ...',
    lifeLine: 'जिंदगी दी लकीर', heartLine: 'दिल दी लकीर', fateLine: 'किस्मत दी लकीर',
    selectLanguage: 'बोली चुनो', language: 'बोली',
    left: 'खब्बा हत्थ', right: 'सज्जा हत्थ',
    cancel: 'रद्द करो', delete: 'मिटाओ', getStarted: 'शुरू करो',
    noReadings: 'अजें तक कोई रीडिंग नेईं',
    welcomeTitle: 'तुंदा हत्थ इक कहानी दस्सदा ऐ',
  },
  ks: {
    ...base,
    appName: 'ہاتھ ریکھا', tagline: 'تُہُندس ہاتھس مَنز پرانہٕ عِلم',
    login: 'سائن اِن', signup: 'اکاؤنٹ بناوو', logout: 'سائن آوٗٹ',
    home: 'ہوم', readings: 'ریڈنگ', profile: 'پروفایِل',
    scanPalm: 'ہاتھ سکین کرو', analyzing: 'ہاتھ پرنہٕ آمُت...',
    lifeLine: 'زِندگی لکیر', heartLine: 'دِل لکیر', fateLine: 'نصیب لکیر',
    selectLanguage: 'زَبان چُنہٕ', language: 'زَبان',
    left: 'کھبہٕ ہاتھ', right: 'ژیٹھہٕ ہاتھ',
    cancel: 'رد', delete: 'مِتاوو', getStarted: 'شروع کرو',
    noReadings: 'ابی کانہہ ریڈنگ نہٕ',
    welcomeTitle: 'تُہُند ہاتھ اِک قصہ آکھان',
  },
  ne: {
    ...base,
    appName: 'हस्तरेखा', tagline: 'तपाईंको हत्केलामा पुरातन ज्ञान',
    login: 'साइन इन', signup: 'खाता बनाउनुहोस्', logout: 'साइन आउट',
    email: 'इमेल ठेगाना', password: 'पासवर्ड', name: 'पूरा नाम',
    dob: 'जन्म मिति', gender: 'लिंग', male: 'पुरुष', female: 'महिला', other: 'अन्य',
    loginTitle: 'फेरि स्वागतम', loginSubtitle: 'तपाईंको हत्केलाको रहस्य खोल्नुहोस्',
    home: 'होम', readings: 'रिडिङ', profile: 'प्रोफाइल',
    scanPalm: 'हत्केला स्क्यान गर्नुहोस्', takePicture: 'फोटो लिनुहोस्',
    chooseGallery: 'ग्यालरीबाट छान्नुहोस्', analyzing: 'हत्केला पढिँदैछ...',
    analysisTitle: 'तपाईंको हस्तरेखा विश्लेषण',
    lifeLine: 'जीवन रेखा', heartLine: 'मुटु रेखा', headLine: 'मस्तक रेखा',
    fateLine: 'भाग्य रेखा', sunLine: 'सूर्य रेखा',
    noReadings: 'अहिले सम्म कुनै रिडिङ छैन',
    selectLanguage: 'भाषा छान्नुहोस्', language: 'भाषा',
    left: 'बाँया हात', right: 'दाहिना हात', chooseHand: 'कुन हात?',
    cancel: 'रद्द गर्नुहोस्', delete: 'मेटाउनुहोस्', getStarted: 'सुरु गर्नुहोस्',
    welcomeTitle: 'तपाईंको हत्केलाले कथा भन्छ',
    welcomeBody: 'प्राचीन भारतीय हस्तसामुद्रिक, वैदिक ज्योतिष र पुराणहरूबाट ज्ञान पाउनुहोस्',
  },
  sat: {
    ...base,
    appName: 'ᱦᱟᱥᱛᱟᱨᱮᱠᱷᱟ', tagline: 'ᱟᱯᱮᱱᱟᱜ ᱦᱟᱛᱮ ᱯᱩᱨᱟᱱᱟ ᱜᱮᱭᱟᱱ',
    login: 'ᱥᱟᱭᱤᱱ ᱤᱱ', signup: 'ᱠᱷᱟᱛᱟ ᱢᱮᱱᱟᱜ', logout: 'ᱥᱟᱭᱤᱱ ᱟᱣᱴ',
    home: 'ᱦᱚᱢ', readings: 'ᱨᱤᱰᱤᱝ', profile: 'ᱯᱨᱚᱯᱷᱟᱭᱤᱞ',
    scanPalm: 'ᱦᱟᱛ ᱥᱠᱟᱱ ᱢᱮᱱᱟᱜ', analyzing: 'ᱦᱟᱛ ᱯᱟᱲᱦᱟ ᱦᱩᱭᱩᱜ...',
    lifeLine: 'ᱦᱤᱨᱤ ᱞᱟᱦᱟ', heartLine: 'ᱦᱤᱭᱟ ᱞᱟᱦᱟ', fateLine: 'ᱵᱷᱟᱜᱤ ᱞᱟᱦᱟ',
    selectLanguage: 'ᱵᱷᱟᱥᱟ ᱧᱟᱢ', language: 'ᱵᱷᱟᱥᱟ',
    left: 'ᱴᱷᱮᱱ ᱦᱟᱛ', right: 'ᱞᱟᱭᱠᱟᱛ ᱦᱟᱛ',
    cancel: 'ᱵᱟᱛᱤᱞ', delete: 'ᱢᱤᱛᱟᱣ', getStarted: 'ᱥᱩᱨᱩ ᱢᱮᱱᱟᱜ',
    noReadings: 'ᱟᱹᱰᱤ ᱨᱤᱰᱤᱝ ᱵᱟᱝ',
    welcomeTitle: 'ᱟᱯᱮᱱᱟᱜ ᱦᱟᱛ ᱠᱚᱛᱷᱟ ᱴᱷᱟᱶᱛᱮᱫᱟ',
  },
  bo: {
    ...base,
    appName: 'हस्तरेखा', tagline: 'नों हाथनि गेदेर पुरानि बिथाङ',
    login: 'साइन इन', signup: 'एकाउण्ट दाव', logout: 'साइन आउट',
    home: 'होम', readings: 'रिडिङ', profile: 'प्रफाइल',
    scanPalm: 'हाथ स्कैन दाव', analyzing: 'हाथ पोरब्ला...',
    lifeLine: 'जिउ लाइन', heartLine: 'निया लाइन', fateLine: 'हादुं लाइन',
    selectLanguage: 'भाषा दाव', language: 'भाषा',
    left: 'गुबुन हाथ', right: 'नाजा हाथ',
    cancel: 'बाद दाव', delete: 'हनाय', getStarted: 'फिसा दाव',
    noReadings: 'अजि रिडिङ नङा',
    welcomeTitle: 'नों हाथनि एबा बिजाथि दं',
  },
};

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    AsyncStorage.getItem('language').then(val => {
      const validCodes = ALL_LANGUAGES.map(l => l.code);
      if (val && validCodes.includes(val as Language)) {
        setLanguageState(val as Language);
      }
    });
  }, []);

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    AsyncStorage.setItem('language', lang);
  }, []);

  const t = useCallback((key: string) => {
    return translations[language]?.[key] ?? translations['en'][key] ?? key;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
